In [ ]:
import torch

In [ ]:
python_list = [1.0, 2.0, 3.0, 4.0, 5.0]

torch_tensor = torch.tensor([1.0, 2.0, 3.0, 4.0, 5.0])

In [ ]:
for i in range(len(python_list)):
    print("{}번째 element {} 의 memory 주소 : {}".format(i,torch_tensor[i],id(python_list[i])))

0번째 element 1.0 의 memory 주소 : 139705760512240
1번째 element 2.0 의 memory 주소 : 139705760512048
2번째 element 3.0 의 memory 주소 : 139705760512304
3번째 element 4.0 의 memory 주소 : 139705760511408
4번째 element 5.0 의 memory 주소 : 139705760512144


### TORCH.TENSOR.DATA_PTR


=> Returns the address of the first element of self tensor.



In [ ]:
for i in range(len(torch_tensor)):
    print("{}번째 element {} 의 memory 주소 : {}".format(i,torch_tensor[i],torch_tensor[i].data_ptr()))

0번째 element 1.0 의 memory 주소 : 127440384
1번째 element 2.0 의 memory 주소 : 127440388
2번째 element 3.0 의 memory 주소 : 127440392
3번째 element 4.0 의 memory 주소 : 127440396
4번째 element 5.0 의 memory 주소 : 127440400


### TORCH.EINSUM

=> Sums the product of the elements of the input operands along dimensions specified using a notation based on the Einstein summation convention.

=> For example, matrix multiplication can be computed using einsum as torch.einsum(“ij,jk->ik”, A, B). Here, j is the summation subscript and i and k the output subscripts (see section below for more details on why).

In [ ]:
q = torch.randn(16,512)
k = torch.randn(16,512)
neg = torch.randn(16,512,20)

l_pos = torch.einsum('nc,nc->n', [q, k]).unsqueeze(-1)
l_neg = torch.einsum('nc,nck->nk', [q, neg])

print(l_pos.shape)
print(l_neg.shape)

torch.Size([16, 1])
torch.Size([16, 20])




**파이썬에서 숫자는 객체다**

* In boxing, the value stored on the stack is copied to the object stored on heap memory, whereas unboxing is the opposite.


* In Unboxing, the object's value stored on the heap memory is copied to the value type stored on stack.

**파이썬에서 리스트는 연속된 객체의 컬렉션이다.**

* Python lists have no way of optimizing the layout of their contents in memory as they are indexable collections of pointers to python.

**파이썬 인터프리터는 최적화를 거치는 컴파일된 코드보다 느리다.**

In [ ]:
Tensor_A = torch.tensor([[1,2],[3,4],[5,6]])

In [ ]:
Tensor_B = torch.transpose(Tensor_A,0,1)

In [ ]:
print(Tensor_A, Tensor_A.shape)
print()
print(Tensor_B, Tensor_B.shape)

tensor([[1, 2],
        [3, 4],
        [5, 6]]) torch.Size([3, 2])

tensor([[1, 3, 5],
        [2, 4, 6]]) torch.Size([2, 3])


In [ ]:
print("Tensor_A's pointer : {}".format(Tensor_A.data_ptr()))
print("Tensor_B's pointer : {}".format(Tensor_B.data_ptr()))

Tensor_A's pointer : 127572288
Tensor_B's pointer : 127572288


In [ ]:
Tensor_C = Tensor_A.clone()

In [ ]:
print("Tensor_A's pointer : {}".format(Tensor_A.data_ptr()))
print("Tensor_B's pointer : {}".format(Tensor_B.data_ptr()))
print("Tensor_C's pointer : {}".format(Tensor_C.data_ptr()))

Tensor_A's pointer : 127572288
Tensor_B's pointer : 127572288
Tensor_C's pointer : 127573184


In [ ]:
Tensor_A = torch.tensor([[1,2],[3,4],[5,6]])
Tensor_B = torch.transpose(Tensor_A,0,1)

print("Before Insert")

print(Tensor_A)
print()
print(Tensor_B)
print()

Tensor_B[0] = torch.tensor([7,8,9])

print("After Insert")

print(Tensor_A)
print()
print(Tensor_B)

Before Insert
tensor([[1, 2],
        [3, 4],
        [5, 6]])

tensor([[1, 3, 5],
        [2, 4, 6]])

After Insert
tensor([[7, 2],
        [8, 4],
        [9, 6]])

tensor([[7, 8, 9],
        [2, 4, 6]])


### Pytorch with GPU

In [ ]:
import torch
from torchvision.io import read_image
from torchvision.models import resnet50, ResNet50_Weights
import time
# Step 1: Initialize model with the best available weights
weights = ResNet50_Weights.DEFAULT
model = resnet50(weights=weights)
model.eval()

input = torch.randn(1,3,224,224)

start = time.time()
output = model(input)
print("Forward Time with CPU : {}".format(time.time()-start))

Forward Time with CPU : 0.18960905075073242


In [ ]:
from torchvision.io import read_image
from torchvision.models import resnet50, ResNet50_Weights
import time
# Step 1: Initialize model with the best available weights
weights = ResNet50_Weights.DEFAULT
model = resnet50(weights=weights)
model = model.cuda()
model.eval()

input = torch.randn(1,3,224,224).cuda()

start = time.time()
output = model(input)
print("Forward Time with GPU : {}".format(time.time()-start))

Forward Time with GPU : 0.010813713073730469


In [ ]:
CPU_tensor = torch.tensor([[1,2],[3,4],[5,6]])

In [ ]:
GPU_tensor = CPU_tensor.cuda()

In [ ]:
print("Tensor_CPU's pointer : {}".format(CPU_tensor.data_ptr()))
print("Tensor_GPU's pointer : {}".format(GPU_tensor.data_ptr()))

Tensor_CPU's pointer : 2774537280
Tensor_GPU's pointer : 139727996977152
